import type {Metadata} from 'next';
import {Inter} from 'next/font/google';

import React from 'react';
import Footer from './(providers)/(root)/_components/Footer';
import Header from './(providers)/(root)/_components/Header';
import MainWrapper from './(providers)/(root)/_components/MainWrapper';
import ProvidersLayout from './(providers)/layout';
import './globals.css';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'WhatSurv?',
  description: 'Generated by create next app',
};

export type HTMLLayoutProps = {
  children: React.ReactNode;
};

export default function HTMLLayout({children}: HTMLLayoutProps) {
  return (
    <ProvidersLayout>
      <Header />
      <MainWrapper>{children}</MainWrapper>
      <Footer />
    </ProvidersLayout>
  );
}
